clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    vault:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
    travel-agency:
      labels:
        istio-discovery: enabled
        istio.io/rev: default
    travel-portal:
      labels:
        istio-discovery: enabled
        istio.io/rev: default
    travel-control:
      labels:
        istio-discovery: enabled
        istio.io/rev: default
    istio-cni:
      labels:
        istio-discovery: enabled
    istio-system:
      labels:
        istio-discovery: enabled
    tempo:
      labels:
        istio-discovery: enabled
    openshift-tempo-operator:
      labels:
        openshift.io/cluster-monitoring: true
      operatorGroup: true
      targetNamespaces:
    openshift-opentelemetry-operator:
      operatorGroup: true
      targetNamespaces:
    openshift-cluster-observability-operator:
      labels:
        openshift.io/cluster-monitoring: true
      operatorGroup: true
      targetNamespaces:

  subscriptions:
    servicemesh:
      name: servicemeshoperator3
      channel: stable-3.2
      csv: servicemeshoperator3.v3.2.3
      installPlanApproval: Manual
    servicemesh-console:
      name: kiali-ossm
    distributed-tracing:
      name: tempo-product
      namespace: openshift-tempo-operator
    opentelemetry:
      name: opentelemetry-product
      namespace: openshift-opentelemetry-operator
    cluster-observability:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

  argoProjects:
    - hub
    - servicemesh
    - travelops
    - distributed-tracing

  applications:
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    mysql:
      name: mysqldb
      namespace: travel-agency
      argoProject: travelops
      path: charts/all/travelops/mysqldb
    agency:
      name: travel-agency
      namespace: travel-agency
      argoProject: travelops
      path: charts/all/travelops/travel-agency
    portal:
      name: travel-portal
      namespace: travel-portal
      argoProject: travelops
      path: charts/all/travelops/travel-portal
    control:
      name: travel-control
      namespace: travel-control
      argoProject: travelops
      path: charts/all/travelops/travel-control
    servicemesh:
      name: servicemesh
      namespace: istio-system
      argoProject: servicemesh
      chart: servicemesh
      chartVersion: 0.1.*
      overrides:
        - name: servicemesh.version
          value: v1.24.3
    temposttack:
      name: tempostack
      namespace: tempo
      argoProject: distributed-tracing
      path: charts/all/tempostack
      extraValueFiles:
        - /values-distributed-tracing.yaml
    tracing:
      name: distributed-tracing
      namespace: istio-system
      argoProject: distributed-tracing
      path: charts/all/distributed-tracing
      extraValueFiles:
        - /values-distributed-tracing.yaml

servicemesh:
  istio:
    values:
      meshConfig:
        enableTracing: true
        extensionProviders:
          - name: zipkin
            zipkin:
              service: dev-collector.istio-system.svc.cluster.local
              port: 9411
        defaultProviders:
          tracing:
            - zipkin
        discoverySelectors:
          - matchLabels:
              istio-discovery: enabled
  istiocni:
    name: default
    namespace: istio-cni
  peerauthentications:
    - name: default
      namespace: istio-system
      spec:
        mtls:
          mode: STRICT
  monitoring:
    enabled: true
    podMonitorNamespaces:
      - travel-agency
      - travel-portal
      - travel-control
