# Default values for control.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appVersion: v1

replicaCount: 1

image:
  registry: quay.io
  repository: kiali
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1

service:
  name: http
  type: ClusterIP
  port: 8080

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli

rbac:
  serviceAccountName: travelops-sa

gateway:
  enabled: true
  namespace: travel-control
  gatewayClassName: istio
  port: 80
  hostname: ""
  path: "/"
  allowedRoutes:
    from: Same

consoleLink:
  imageURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYEAYAAACw5+G7AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGYktHRAAAAAAAAPlDu38AAAAJcEhZcwAAAGAAAABgAPBrQs8AAAAHdElNRQfqBhASHwRxx43iAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA2LTE2VDE4OjMxOjA0KzAwOjAwcuWO8QAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNi0xNlQxODozMTowNCswMDowMAO4Nk0AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDYtMTZUMTg6MzE6MDQrMDA6MDBUrReSAAAKHElEQVRYw9WXZ3SWVRLHf/M8b0l505ESiCRAAgSQXqSmUGMokeKCIJFIEylSwlIUVhBQ0FV6UYqQ6AJHF9CoSCAQMLRIWUINTVIhgUACKe/7Pnc/bAQ8i7ueXT1ndz7dc8+dmf/c+d+ZO/B/LvL7mW7ydRgAarNRDcA0zvIMgDaQEgBVohoDUJPXAEg2KQD3CzeHAdwuqNcA4OzAbdt+2Yv22wFu2bJlSwRaDmkeBXTRPfQjIM9bDltjACpMxhxeB25QZu4AKktFW3oB92ilZUqWqrC3BXn+vtWvBaCZMouWAjyzuNspLL/k1fTfA28aGVGCK9i3q5qUShOtsaUPqP1MdQT6DsLN2G9MDj3OX61h2twmtbii3sSjdncqZJ40sF7Eh6fE7+YKpcsS7d6ZYqmFO6kZXhhFs1zjriINfAeVeqsKmdbib11fwcOIc3wj4ymG09O+a/ozCq1Zc2ENwOmGdQcCNOp5bSaAEShmALWVeABsHAPgqvQHqm0f8MZSIP9OcG6BZQQ3NA3XiEaUkiB1YvdJN+kjw9uIylAnaF0whFQc2LKnYAF+LD8uPeVpqLKDUKpSPUijiDZ45n+AxhG8tpuJU9vk9JYVslOLVw1udjKuOtsYNYBb8qax5GcUOvV0yCiA+nOulwHsbl93FQDdSHePAHzRfKsAXuT7vgf6btNk2wHyfd0D5rsbLJMkmT82iGqmFJdDqxIIrrezbWSnNDX6WefgI4fGkOJJ1Wde3kkv+2flMSMLiSSYzLHD8Fa71L7YQFzULrVsiK/6lgy1eP8ybPQga3RnEmSucl921ljCPDlcN14L067or4CWLEmW83gKLG99eQj+QAhCDhgbSPBbANowpveoD2ol9fo2AE7TPbQI0Dhn6gqySuxnlzAp+eTqwOwxzMv1unBo4F3mtajbt7++k7UhWzo2d79NkXm4ZcrdD0Aza/Xjx8PY9U9HbZkG3cbH3QLxvDXimgOYLSdlOah4c7AM1efLOnumGtL5OokspWThCDLpSXheCvXVs8ascZ+oDdQiP/ucwPKwy7MBuM+FwGJQ4QyanQsE0P7FEYBQ5pIKKBSAZGh9ge63p2dNKVjBlpS9H63RP+T9kHfap5QXsahRw66Lfe4Cr8tmazlwTn0HwB2sJycB3vQb2g9UnJ6fEQ7WNfbrACvXjmoB7Je3tW5AmeiyDqRQ3WR0l2SWyOesWenkFGnqm60jlRM3o/2CHiZgBYd9BoFyMDY+HThK4xEmoJQySa3klxMIkpbowCy18UF/BmceS6ttHyrV3QN8QkpXKs/6AZ37+GwCZkqBdTNwVH1NBSA4sAB2PJqWAWc5EDMFJNiZc74EKgZpPk4bnDqzzxvoQl/SAUeLmMj5oEzFsTW99gdjeBg5nhuHirc6IpOGHxQnufqMXdc14B25HuENnKbri1FAKbp0qOwRJZUB6CBHpCMQUfxNYaIjSeJzos53dd5Wg4Ovtz/gupkic6LrPjcncEJ9WaklWACF4AD8uCOrAVfxig4BqS/RXj2B/dL8SfXRecEtBGSo7XSO8LQEqE+ptWsHLtIWt4qtaq0MITl8pQbKqg5EvQUUUeC5CRAEZ6UZ2yOLckb6E4nlnvfNhVYDq2NT+SKTUOhz3V9z2wrkqO+1RMBO2RPLtaqseTa1o143wFN9WO0scEvNfVJ51o6UmkEl4FT9QGVTX03I2qaSKOfW6YEMxopfx2QNaERxw/SftB7d+CNLD3fdnZPRKr4onXl/PBaXLNsN+x00l3a2ZeXTgGmq0a9qHP7UNf8AnOB89WmAn0x50rETHntiAGV/4PAEU6hfsGerklEEqzSVnpcj/cnmRECEBpSQy4RKLfVvnCtAx4wGagfzAchgD05A/5VtsRyDu6DGcZJEYDSB/9LlPtUAmGC95ToegHyuSQRCNYLUeg2I5ubZn1hrPPZoebhnVIIv1pdiWOJcN7uNoaJ8XEmM2Rtn6eXisdYk4F05+6sCKOCqPQwklRfysoCFavyTjjXdFP4GIJYcc0dwjMmOy1tlS+ESHaVd9RpqO7VpcyNFA9lFq6TNQA30u6sAA/WQQsWP3USo2sZu7J5UXVmeT7lpkvW2Yw9VirxzDt1fANSgmdEBMOPyT2gcj+W3Kg0uZQCtCM03A72IeFIADu4XgQyWThIAUl0KZEvAMumFjmpynM9oRsjBHzVgodTe2xrwkKiEIMAdV/VVZTY8HmVEdVBpQLLN4hds/ka967+/4Rl9pnx6qdP398sa422fWFr4AKClxDwkXEXlygSYcFU9QeLJ+zIQxI/Iu4dBmpH0BPyl5kSPo6ASPUyat3RUN+hP995dqRA/3Cz+MhYHe1Pe1CFq+cQmZX8BuUzs2XBgoPS25QJ36N8wCbiP2dwTuMNoAFmvvWgOp9StildheSPSLs74PsfaD7vqaEQ/CORg1VF1tptLgFjZZAoC8hgKQKi0OukGco7eC78A1UPvl/8qWFydUwHyBp1rA+ytVqPOdOAq4SIgkfYrakDYHhlJqqybNYpsXqLNZ0fVA60v/p8n6BDVbuIk/IFckop2gyjuHdoAXGJWRhrgRpzjNCCEEAn0VN6FQVx23es5/HhNjNxFFzelbmdO5uq0o42fw2F+yRpvb0GG38xasfIHyvQc8/pb/qB10D956wqMWxDUNPnPYB9ashHE7cDiBF+QeUYVAIaZW9FZvyMd1Tb1Uth0EsmUuEV+5HCc1GsedJDdTJm/g1QO4nH3u8d+o+99VLoVwDonbxKAV0VgNkDR/CtH3G2AUwZY8oGX1CBZCHqw6bWKINhzYm1rtZ4Vl4+lZY3YyCjLRJek13dgqp3drIa1kIVVp9XJ2pdIkzPPJ09euJLehbuyBuSPAlNDa5gzRnxkGG/a9lCXHdStWU19IhvxjXHKC3yB3m8uSl0i9MRAtVadNPrM3KctkKr67CvNiGUfP+D5WADLW59bBlCyM+QBgFv5lS8B5Gtt6T8YLV0AiFZvAfAFjYHqn//wp1Igr+hoXoDZST4RRlz4CYrJVRti8yUSH2nVbpI6Q7IqK4zgoDomnbOOY6Ecj4py6QHcr9KYRhLCucAN3AOcea0wqxQ6bYtggozR/BOmysfKbl9xq7aRo+dY3gPyCXR++5uMlM2XdG+OC0gwfpRJiHMoh0Bd1Lc4v/L5TDzVdbGFrlNb0JjUpAeXmUFx4GrK0dRu6yh81W4u5T9LP1nN5DO1ZDFfMTZjnlqswh88dXWMtJZU203aSawx2/48HsY408e2qxRDevqXLX/TmTiMMBDQopQbivAih+kmiKeaIR+C2uEzu8RJL7gd7f6y+SJQS7lJCBhvGHscf5RT+kjLc0YX3lbTjUBQ2zlo5AIGuvhggZOdkkseVrWH8jsO9c07dC0AUO/K+wDaq0Y0gLFdogFwUVMBaK9mAIjuHADgbOs1DgFzZvY0FKSnp6f/5yj+5+XvO4AIw7tLOP8AAAAASUVORK5CYII="
